# Production Environment Configuration
name: production
protection_rules:
  - type: required_reviewers
    required_reviewers: 1
  - type: wait_timer
    wait_timer: 2
variables:
  DEPLOYMENT_TIMEOUT: "600"
  HEALTH_CHECK_RETRIES: "5"
  ENVIRONMENT_NAME: "production"