name: IoTFlow CI

on:
  push:
    branches: [ "master", "main", "develop" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      iotdb:
        image: apache/iotdb:1.3.0-standalone
        ports:
          - 6667:6667
        options: >-
          --health-cmd "nc -z localhost 6667 || exit 1"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 15

      mqtt:
        image: eclipse-mosquitto:2.0
        ports:
          - 1883:1883
        options: >-
          --health-cmd "timeout 5 bash -c '</dev/tcp/localhost/1883' || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup MQTT config
      run: |
        mkdir -p /tmp/mosquitto/config
        cat > /tmp/mosquitto/config/mosquitto.conf << EOL
        listener 1883
        allow_anonymous true
        log_type error
        EOL

    - name: Setup environment
      run: |
        cp .env.example .env || touch .env
        cat >> .env << EOL
        FLASK_ENV=testing
        TESTING=true
        DATABASE_URL=sqlite:///test_iotflow.db
        REDIS_URL=redis://localhost:6379/1
        IOTDB_HOST=localhost
        IOTDB_PORT=6667
        IOTDB_USERNAME=root
        IOTDB_PASSWORD=root
        IOTDB_DATABASE=root.iotflow
        MQTT_HOST=localhost
        MQTT_PORT=1883
        IOTFLOW_ADMIN_TOKEN=test_token
        EOL

    - name: Wait for services
      run: |
        echo "Waiting for services to be ready..."
        timeout 60 bash -c 'until nc -z localhost 6379; do sleep 1; done'
        timeout 60 bash -c 'until nc -z localhost 6667; do sleep 1; done'
        timeout 60 bash -c 'until nc -z localhost 1883; do sleep 1; done'
        echo "All services are ready!"

    - name: Run linting
      run: |
        pip install flake8 black
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        black --check src/

    - name: Initialize database
      run: |
        echo "y" | python init_db.py

    - name: Run unit tests
      run: |
        python -m pytest tests/ -v --tb=short
      if: always()

    - name: Start application
      run: |
        python app.py &
        sleep 15
        # Verify app is running
        curl -f http://localhost:5000/health || exit 1

    - name: Run end-to-end tests
      run: |
        python tests/test_end_to_end.py

    - name: Generate coverage report
      run: |
        pip install coverage
        coverage run -m pytest tests/
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
      if: always()

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          logs/
          *.log
          test-results.xml
      if: always()